# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "c7e3adcc013d972e33bbdc77bd56c6bdd40c4faa"

[[deps.AoC25]]
path = "."
uuid = "ff143683-340d-441b-8c9d-b0176b6adda3"
version = "0.1.0"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"
