name = "AoC25"
uuid = "ff143683-340d-441b-8c9d-b0176b6adda3"
version = "0.1.0"
authors = ["José Bayoán Santiago Calderón <naoyabpr@gmail.com>"]

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
Unicode = "1.11.0"
