name = "AoC25"
uuid = "ff143683-340d-441b-8c9d-b0176b6adda3"
version = "0.1.0"
authors = ["José Bayoán Santiago Calderón <naoyabpr@gmail.com>"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
Satisfiability = "160ab843-0bc6-4ba4-9585-b7478b70f443"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
Z3 = "06b161dc-0161-11ea-0f74-41f836f4024b"

[compat]
Combinatorics = "1.0.3"
Graphs = "1.13.2"
Intervals = "1.10.0"
Satisfiability = "0.2.0"
Unicode = "1.11.0"
Z3 = "1.0.4"
