name = "AoC25"
uuid = "ff143683-340d-441b-8c9d-b0176b6adda3"
version = "0.1.0"
authors = ["José Bayoán Santiago Calderón <naoyabpr@gmail.com>"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
Combinatorics = "1.0.3"
Intervals = "1.10.0"
Unicode = "1.11.0"
